#ifndef TPMCERT_NCRYPT_PROVIDER_H
#define TPMCERT_NCRYPT_PROVIDER_H

#include <bcrypt.h>
#include <ncrypt.h>

#ifndef BCRYPT_MAKE_INTERFACE_VERSION
#define BCRYPT_MAKE_INTERFACE_VERSION(major, minor) ((major << 16) | minor)
#endif

typedef struct _NCRYPT_KEY_STORAGE_FUNCTION_TABLE {
    BCRYPT_INTERFACE_VERSION Version;
    SECURITY_STATUS (WINAPI *OpenProvider)(NCRYPT_PROV_HANDLE*, LPCWSTR, DWORD);
    SECURITY_STATUS (WINAPI *OpenKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE*, LPCWSTR, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *CreatePersistedKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE*, LPCWSTR, LPCWSTR, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *GetProviderProperty)(NCRYPT_PROV_HANDLE, LPCWSTR, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *GetKeyProperty)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, LPCWSTR, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *SetProviderProperty)(NCRYPT_PROV_HANDLE, LPCWSTR, PBYTE, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *SetKeyProperty)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, LPCWSTR, PBYTE, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *FinalizeKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, DWORD);
    SECURITY_STATUS (WINAPI *DeleteKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, DWORD);
    SECURITY_STATUS (WINAPI *FreeProvider)(NCRYPT_PROV_HANDLE);
    SECURITY_STATUS (WINAPI *FreeKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE);
    SECURITY_STATUS (WINAPI *FreeBuffer)(PVOID);
    SECURITY_STATUS (WINAPI *Encrypt)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, PBYTE, DWORD, VOID*, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *Decrypt)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, PBYTE, DWORD, VOID*, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *IsAlgSupported)(NCRYPT_PROV_HANDLE, LPCWSTR, DWORD);
    SECURITY_STATUS (WINAPI *EnumAlgorithms)(NCRYPT_PROV_HANDLE, DWORD, DWORD*, NCryptAlgorithmName**, DWORD);
    SECURITY_STATUS (WINAPI *EnumKeys)(NCRYPT_PROV_HANDLE, LPCWSTR, NCryptKeyName**, PVOID*, DWORD);
    SECURITY_STATUS (WINAPI *ImportKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, LPCWSTR, NCryptBufferDesc*, NCRYPT_KEY_HANDLE*, PBYTE, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *ExportKey)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, NCRYPT_KEY_HANDLE, LPCWSTR, NCryptBufferDesc*, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *SignHash)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, VOID*, PBYTE, DWORD, PBYTE, DWORD, DWORD*, DWORD);
    SECURITY_STATUS (WINAPI *VerifySignature)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, VOID*, PBYTE, DWORD, PBYTE, DWORD, DWORD);
    SECURITY_STATUS (WINAPI *PromptUser)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, LPCWSTR, DWORD);
    SECURITY_STATUS (WINAPI *NotifyChangeKey)(NCRYPT_PROV_HANDLE, HANDLE*, DWORD);
    SECURITY_STATUS (WINAPI *SecretAgreement)(NCRYPT_PROV_HANDLE, NCRYPT_KEY_HANDLE, NCRYPT_KEY_HANDLE, NCRYPT_SECRET_HANDLE*, DWORD);
    SECURITY_STATUS (WINAPI *DeriveKey)(NCRYPT_PROV_HANDLE, NCRYPT_SECRET_HANDLE, LPCWSTR, NCryptBufferDesc*, PUCHAR, DWORD, DWORD*, ULONG);
    SECURITY_STATUS (WINAPI *FreeSecret)(NCRYPT_PROV_HANDLE, NCRYPT_SECRET_HANDLE);
} NCRYPT_KEY_STORAGE_FUNCTION_TABLE, *PNCRYPT_KEY_STORAGE_FUNCTION_TABLE;

#endif
